### ISSUE TITLE
Using PyCharm

### ISSUE THREAD

**Issue by aasith** [LukePeters/User-Login-System-Tutorial#1]
hi,
thanks for a superb tutorial. One of the absolute best. 

However, I am using PyCharm and when rendering the signup page I get an error "form is not defined". I have downloaded and run your code and it is the same error. I have a feeling it is because I am using PyCharm and the IDE gives me som hints about changing the code in the scripts.js file. But I am currently unable to understand how to. 

Happy New Year

**Comment by aasith** [comment]
The problem is solved. The circular import statements are not appreciated. Moved the line "from app import db" from top to the place in the function where it is needed"

**Comment by LukePeters** [comment]
Hello,

How was the position of the import statement causing the error, “form is not defined”?

Thanks,
Luke

**Comment by aasith** [comment]
hi 
I was wrong yesterday. Yesterday I got a problem with the script.js file which I somehow solved. The errors are not connected.

But then today I finally understood that Python does not like the circular import statements and I moved "from app import db" to the function, just before it is needed to insert the user object to the db.

Great tutorial !!!many, many thanks
Christina 

Luke Peters <notifications@github.com> skrev: (30 december 2020 14:15:22 CET)
>Hello,>
>>
>How was the position of the import statement causing the error, “form
>is not defined”?>
>>
>Thanks,>
>Luke>
>>
>> On Dec 30, 2020, at 7:38 AM, aasith <notifications@github.com>
>wrote:>
>> >
>> ﻿>
>> The problem is solved. The circular import statements are not
>appreciated. Moved the line "from app import db" from top to the place
>in teh function where it is needed">
>> >
>> —>
>> You are receiving this because you are subscribed to this thread.>
>> Reply to this email directly, view it on GitHub, or unsubscribe.>
>>
>>
>-- >
>You are receiving this because you modified the open/close state.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/LukePeters/User-Login-System-Tutorial/issues/1#issuecomment-752582627

-- 
Skickat från min Android-enhet med K-9 Mail. Ursäkta min fåordighet.
